server:
  port: 9802 # 服务端口
  servlet:
    context-path: /
spring:
  application:
    name: monster-gateway # eureka的服务名称
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启Eureka服务发现
          lower-case-service-id: true
      routes:
        - id: monster-security
          uri: lb://monster-security
          predicates:
            - Path=/monster-security/**
eureka:
  client:
    service-url:
      # eureka的地址信息（因为eureka也是一个微服务，也要注册到注册中心里）
      defaultZone: http://localhost:9801/eureka
  instance:
    prefer-ip-address: true
